run_type: !mux
    upstream:
        type: 'upstream'
        location: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git'
component: !mux
    security:
        comp: 'powerpc'
        kself_args: 'summary=1'
        subtest: 'security'
    kexec:
        comp: 'kexec'
        kself_args: 'summary=1'
    tpm2:
        comp: 'tpm2'
        kself_args: 'summary=1'
    safesetid:
        comp: 'safesetid'
        kself_args: 'summary=1'
    seccomp:
        comp: 'seccomp'
        kself_args: 'summary=1'
    dexcr:
       comp: 'powerpc'
       subtest: 'dexcr'
